@host = http://localhost:5211

### List all books
GET {{host}}/books
Accept: application/json

### Add a book
POST {{host}}/books
Content-Type: application/json

{
  "title": "Refactoring",
  "author": "Martin Fowler",
  "isbn": "978-0134757599",
  "copiesTotal": 2
}

### Get a book
GET {{host}}/books/REPLACE-WITH-ID
